CREATE TABLE IF NOT EXISTS clientes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historial (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  x1 REAL,
  x2 REAL,
  resultado REAL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos_chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_input TEXT,
  intent TEXT,
  tool_name TEXT,
  tool_args TEXT,
  tool_result TEXT,
  respuesta TEXT,
  ok INTEGER,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
